TRUNCATE TABLE cnae;
TRUNCATE TABLE dados_simples;
TRUNCATE TABLE empresa;
TRUNCATE TABLE estabelecimento;
TRUNCATE TABLE municipio;
TRUNCATE TABLE natureza_juridica;
TRUNCATE TABLE pais;
TRUNCATE TABLE qualificacao_socio;
TRUNCATE TABLE socio;